version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - .db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_postgres_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
